Add a lint check for RSpec
DFE-Digital/refer-serious-misconduct pull request #237
Opened 2022-11-28 13:31 UTC by felixclack

There are variations in how we write our specs, which will likely
continue to vary as other people contribute to the project.

To reduce the cognitive load on the author when writing and the
maintainer when reading, we can auto-format our specs using the RSpec
cops for Rubocop.

These cops mostly follow the style described in `https://betterspecs.org`.

The exceptions added to `rubocop.yml` are to ensure the cops match the
testing styleguide we already have written.

Feel free to modify the cops if you have a strong opinion on any of
them.

This change brings in the default cops and ensures our codebase doesn't
have any violations.

Also, while there I noticed we have 2 time helpers included in the
project. Seeing as Rails provides this already, it makes sense to ditch
Timecop.

2022-11-29 10:18 UTC, vassyz commented on Gemfile
> +  gem "rubocop-rspec", require: false
It's already a dependancy of `rubocop-govuk`. Check the current rules here: https://github.com/alphagov/rubocop-govuk/blob/ce655779e45892db6ac00d6789c652ec2e506748/config/rspec.yml `RSpec/ExampleLength`is already `false`

2022-11-30 10:31 UTC, malcolmbaig commented on spec/forms/users/otp_form_spec.rb
> +    let(:id) { user.id }
Doesn't look like we need this to be a separate let (not used anywhere on its own)

2022-11-30 10:56 UTC, malcolmbaig approved these changes
Linting the specs is a positive, and by and large the changes here are improvements in clarity. 

Happy to approve, but I'd encourage us not to be overly prescriptive when it comes to testing style. For example — with longer, more complex specs, leaning heavily on `let`s and a `subject` defined very early on in the file worsens readability, IMO. Some amount of setup local to the example block and locally-defined helper methods are valid techniques to deal with this. Leaving room for exercising that judgement would be helpful long term.

Would like to see another approval before merge given the wide range of the PR, but otherwise 👍🏼

2022-11-30 11:07 UTC, vassyz commented on .rubocop.yml
> +require:
Is this needed?

2022-11-30 11:10 UTC, steventux requested changes
It feels like there are a lot of changes in this PR which don't relate to RSpec linting so much as general refactoring, it would be good to pick these out either into a separate PR for review or at least separate commits for better future understanding.
eg. there's a refactor of how various date params are passed to forms which seems additional to RSpec linting.

2022-11-30 11:10 UTC, steventux commented on app/forms/referrals/personal_details/age_form.rb
> +      attr_accessor :date_params, :referral
This and other date field changes don't seem to relate to the commit message. 
FWIW I think this is a worthwhile refactor but should either be in another PR or at least another commit, it doesn't relate to RSpec linting.

2022-11-30 11:16 UTC, vassyz commented on app/forms/referrals/personal_details/age_form.rb
> +      attr_accessor :date_params, :referral
Just wanted to say the same thing when I saw your comment. I was wondering if it could come out of a lint error, but don't think that is the case.

2022-11-30 11:22 UTC, vassyz approved these changes
Looks good. I think this PR does too much, but you might as well merge it before you have more conflicts to fix.

2022-11-30 12:06 UTC, steventux approved these changes

2022-11-30 14:45 UTC, merged