Email user a link to referral when it's created
DFE-Digital/refer-serious-misconduct pull request #513
Opened 2023-02-22 09:20 UTC by paulodeon

### Context

To allow users to access their referral if they partially complete it

### Changes proposed in this pull request

https://tra-digital-design-history.herokuapp.com/teacher-misconduct/sending-users-a-link-to-access-their-referral/

* Add referral link email
* Add callback to send email when creating referral
* Rename `send_otp` for consistency with the new mailer function
* Added tests

### Guidance to review

### Link to Trello card

[](https://trello.com/c/iud9pIjs/1210-referrals-design-history-change-email-user-a-link-to-their-referral-when-started)

### Checklist

- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally

2023-02-22 09:56 UTC, gpeng requested changes

2023-02-22 09:56 UTC, gpeng commented on app/models/user.rb
>      Referral.find_or_create_by!(
This doesn't feel like it belongs in here to me. We're making the `User` need to know about referrals and mails and eligibility checks. What about `ReferralsService::Create.call(stuff:...` that does all of the things?

2023-02-22 10:11 UTC, vassyz commented on app/controllers/referrals_controller.rb
> +        &:send_referral_link_to_user
Why are you sending it as a block? I'd call the mailer with the `new_referral` argument instead of user. Selecting the `latest_referral` instead of the newly created referral seems not ideal to me.

2023-02-22 11:46 UTC, paulodeon commented on app/models/user.rb
>      Referral.find_or_create_by!(
The user has a `has_many :referrals` so referral functionality within the user object seems reasonable to me. This function was already here and all I added was the ability to pass a block (see other comment). Also there was no existing service objects in the project. Given that, this would be my preferred solution in this case, however I'm also happy to add a service object here.

2023-02-22 11:47 UTC, paulodeon commented on app/controllers/referrals_controller.rb
> +        &:send_referral_link_to_user
Rails `find_or_create_by` takes a block which is passed to create if the record is created. I have made the `find_or_create_referral!` method consistent with that. If the record is created the `send_referral_link_to_user` method is called on the newly created record.

Good point on `latest_referral` fixed.

2023-02-22 12:17 UTC, paulodeon commented on app/controllers/referrals_controller.rb
> +        &:send_referral_link_to_user
Actually I take your other point as well

2023-02-22 12:19 UTC, paulodeon commented on app/models/user.rb
>      Referral.find_or_create_by!(
I've put the mailer call into the controller which is consistent with the other mailer calls in the app

2023-02-22 12:22 UTC, tavy88 commented on app/models/user.rb
>      Referral.find_or_create_by!(
This method seems a bit odd as I don't think `User` should know about `Eligibility`. Feels like `Referral` should know about it. Wonder if you could do something to limit the knowledge of `User` just to `referral` here?

2023-02-22 12:36 UTC, paulodeon commented on app/models/user.rb
>      Referral.find_or_create_by!(
Ok, it seems that wasn't liked! I removed that from the `User` model and it all sits at the controller level now, very clear, consistent with the rest of the app and easy to extract to a service object should we want to later

2023-02-22 15:50 UTC, tavy88 commented on app/controllers/referrals_controller.rb
> +
Much better!

2023-02-22 15:54 UTC, tavy88 approved these changes
LGTM

2023-02-24 13:12 UTC, gpeng approved these changes

2023-02-24 13:12 UTC, gpeng commented on app/controllers/referrals_controller.rb
>    def new
This action seems weird that we're doing all of this in a GET request. I realise it didn't get introduced here, just sayin'.

2023-02-24 14:03 UTC, paulodeon commented on app/controllers/referrals_controller.rb
>    def new
I think the create is unused here as well but let's clean this up later.

It is idempotent and it is accessed through a redirect from the otp controller (we need a get for that) so I think it's reasonable

2023-02-24 14:04 UTC, merged