1250 - Case workers return to original url after login
DFE-Digital/refer-serious-misconduct pull request #526
Opened 2023-02-28 12:25 UTC by tavy88

### Context

Case workers return to original url after login

### Changes proposed in this pull request

If a case worker accesses any url under `/support/*` or `/manage/*`, but they are not authenticated, they will return to the original url after login.

### Link to Trello card

### Checklist

- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally

2023-02-28 12:26 UTC, tavy88 commented on app/controllers/staff/sessions_controller.rb
> +
Capybara does not follow redirects so it's pretty hard to test this behaviour here.

2023-02-28 14:01 UTC, paulodeon commented on app/controllers/staff/sessions_controller.rb
> +
Pretty certain capybara does follow redirects and the above should work, have you tried it yet?

2023-02-28 14:43 UTC, tavy88 commented on app/controllers/staff/sessions_controller.rb
> +
Yep it doesn' t work :)

2023-02-28 15:44 UTC, tavy88 commented on app/controllers/staff/sessions_controller.rb
> +    path = stored_location || request.referer
This exact thing happened to me. I guess it's when you don't have a user in the session in which case it is nil.

2023-02-28 15:45 UTC, tavy88 commented on config/routes.rb
> +    path: "",
Yep. Confirmed with @gpeng -> we don't want `/staff/` at all in the urls.

2023-02-28 15:46 UTC, paulodeon commented on app/controllers/staff/sessions_controller.rb
> +    path = stored_location || request.referer
If it's good enough for devise... https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/devise/controllers/helpers.rb#L215

2023-02-28 16:25 UTC, gpeng requested changes

2023-03-01 09:37 UTC, gpeng commented on app/controllers/staff/sessions_controller.rb
> +    path = stored_location_for(resource)
Naming this `path` is a bit confusing if we don't know whether it's a URL or a path. `stored_location` maybe?

2023-03-01 09:39 UTC, gpeng commented on spec/system/manage/case_worker_returns_to_original_url_after_login_spec.rb
> +           type: :system do
I don't think we need type as have infer from location on

2023-03-01 09:39 UTC, gpeng approved these changes

2023-03-01 11:34 UTC, merged