1306 - Use the email templates from the new Notify service
DFE-Digital/refer-serious-misconduct pull request #596
Opened 2023-03-16 13:35 UTC by tavy88

### Context

Use the email templates from the new Notify service

### Changes proposed in this pull request

We have created a new Notify service just for this project for separation purposes. We want to use
the email templates defined under the new service.

### Guidance to review

We need to do a full regression testing for any notification that we send to ensure everything is working as expected.

### NOTES

I will need to work with either @vassyz or @gpeng because I don't have Azure access (still) and once the API keys are generated in Notify (you can't see them again) so they have to be added in the vaults as we go.

### Link to Trello card

https://trello.com/c/O36wjl4w

### Checklist

- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally

2023-03-17 12:23 UTC, gpeng requested changes

2023-03-17 12:23 UTC, gpeng commented on app/mailers/application_mailer.rb
> +  MANAGE_NOTIFY_TEMPLATE = "7ef13585-7b41-40ea-a5f7-e8df476b8ea3"
We don't need to change the manage templates. We should be using two services in Notify. Emails to referrers should go through the new one we set up but emails to the case workers should come from the existing 'Manage...' service.

2023-03-17 13:46 UTC, gpeng commented on app/mailers/application_mailer.rb
> +  MISCONDUCT_NOTIFY_TEMPLATE = "8a10a1c1-9cc3-4234-af86-c54cedb7ce09"
Sorry to be a pain but the pertinent difference is 'refer' rather than 'manage' so we should name these things with `refer` and `manage rather than misconduct and manage.

2023-03-17 13:57 UTC, vassyz commented on app/mailers/application_mailer.rb
> +  MISCONDUCT_NOTIFY_TEMPLATE = "8a10a1c1-9cc3-4234-af86-c54cedb7ce09"
Sorry, my bad. It should be `refer`.

2023-03-17 15:23 UTC, tavy88 commented on app/mailers/application_mailer.rb
> +  MISCONDUCT_NOTIFY_TEMPLATE = "8a10a1c1-9cc3-4234-af86-c54cedb7ce09"
updated

2023-03-17 16:26 UTC, vassyz approved these changes

2023-03-20 09:14 UTC, vassyz approved these changes

2023-03-20 09:26 UTC, gpeng approved these changes

2023-03-20 09:42 UTC, merged