Referrals employer form - Contact details / their email page
DFE-Digital/refer-serious-misconduct pull request #97
Opened 2022-10-28 08:57 UTC by vassyz

### Context

When making a referral, the email of the person being referred needs to be specified.

https://teacher-misconduct.herokuapp.com/report/teacher-contact-details/email

https://trello.com/c/fF5VwXw5/861-contact-form-add-email-address-page

### Changes proposed in this pull request

Add the following page, accessible from the employer form hub:
<img width="742" alt="Screenshot 2022-10-28 at 15 06 44" src="https://user-images.githubusercontent.com/1636476/198635670-deb4d362-fe1a-4387-bf06-1d96947a1d6f.png">

* Update the routes
* Generate a migration for adding the email to the referrals table.
* Add the form, including validation 
* Link the form to the referral hub

### Guidance to review

To make merging easier, I have updated this PR to be more in-line with @steventux's #94 as I initially had a slightly different approach. One thing I didn't update was to create one from model for the "Contact details" journey. It seems like Steve 
created a [PersonalDetailsForm](https://github.com/DFE-Digital/refer-serious-misconduct/pull/94/files#diff-14e5071aa6cd1cb2cfaad4dc826c6400223159eaff193c2b0182d4d8f4eace21R2). I'd rather have a [model](https://github.com/DFE-Digital/refer-serious-misconduct/pull/97/files#diff-f24b6365d33f4c1eff916a217b38b5a75c2077b24eee898f64f0cfc293f4de12R2) for every form in the "Contact details" section.

### Checklist

- [X] Attach to Trello card
- [X] Rebased main
- [X] Cleaned commit history
- [X] Tested by running locally

2022-10-31 10:13 UTC, malcolmbaig requested changes
Looking good, a few comments left inline

2022-10-31 10:13 UTC, malcolmbaig commented on spec/system/referrals/user_adds_contact_details_email_spec.rb
> +  scenario "Views referral summary sections" do
```suggestion
RSpec.feature "Contact details" do
  scenario "User submits contact details for the referred person" do
```

- with an update to the filename to match the scenario
- and then this spec could be used for all further contact detail steps in the flow

Otherwise spec structure below looks 👌🏼

2022-10-31 10:13 UTC, malcolmbaig commented on app/controllers/referrals_controller.rb
>      # TODO: This needs integration with current_user check
👍🏼

2022-10-31 10:13 UTC, malcolmbaig commented on app/controllers/referrals_controller.rb
> +    @referral ||= Referral.find_or_create_by(id: params[:id])
Should we be creating referrals here? I think it may be safer to limit creation to just one place in the app. If we don't find the referral by ID, then we can redirect them to a sensible starting point (the root?). cc: @steventux

2022-10-31 10:13 UTC, malcolmbaig commented on app/controllers/referrals/contact_details_controller.rb
> +  class ContactDetailsController < ReferralsController
Perhaps this should be:

```suggestion
  class ContactDetails::EmailController < ReferralsController
```

with the actions named `edit`/`update`?

2022-10-31 10:16 UTC, vassyz commented on app/controllers/referrals_controller.rb
> +    @referral ||= Referral.find_or_create_by(id: params[:id])
This was the concern I raised in the standup last week, where the referral should get created. The code above is from @steventux 's PR.

2022-10-31 10:24 UTC, steventux commented on app/controllers/referrals_controller.rb
> +    @referral ||= Referral.find_or_create_by(id: params[:id])
This `find_or_create_by` is here for convenience at the moment while we build out these forms. I wouldn't expect this to remain as is for several reasons.
I had imagined we would create a referral off the back of the eligibility screener as the two records may be associated.
Also a Referral should be associated with a User account.

2022-10-31 10:28 UTC, steventux commented on app/controllers/referrals/contact_details_controller.rb
> +  class ContactDetailsController < ReferralsController
I was wondering about this approach on the personal details forms. Are we better off with multiple slim controllers and fewer actions? I'm happy either way but will make similar changes [here](https://github.com/DFE-Digital/refer-serious-misconduct/pull/94) for consistency.

2022-10-31 10:30 UTC, malcolmbaig commented on app/controllers/referrals_controller.rb
> +    @referral ||= Referral.find_or_create_by(id: params[:id])
👍🏼 Makes sense. I'll add a task to the User accounts work to go through this and make sure referral querying is scoped to current user.

2022-10-31 12:31 UTC, tvararu commented on app/controllers/referrals_controller.rb
> +    @referral ||= Referral.find_or_create_by(id: params[:id])
:+1: thanks @malcolmbaig

2022-10-31 12:32 UTC, tvararu commented on app/controllers/referrals/contact_details_controller.rb
> +  class ContactDetailsController < ReferralsController
I think multiple slim controllers with idiomatic `edit/update` actions, plus each one with its own `FormModel` makes sense :+1:

2022-10-31 15:43 UTC, steventux approved these changes
A question about the boolean db field (more out of ignorance). Otherwise all looks good to me.

2022-10-31 16:43 UTC, vassyz commented on app/forms/referrals/contact_details_email_form.rb
> +    validates_format_of :email_address,
Thanks! That's a lot better.

2022-11-01 08:45 UTC, steventux commented on db/schema.rb
> +    t.boolean "email_known"
Makes sense, I think persisting is right

2022-11-01 09:24 UTC, malcolmbaig approved these changes

2022-11-01 16:19 UTC, merged